[package]
name = "orca-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
orca_whirlpools = "2.0.1"
serde_json = "1.0.139"
solana-client = "2.2.0"
solana-sdk = "2.2.1"
tokio = "1.43.0"
